name: Build for webOS
on: [push, pull_request]
env:
  app_id: inputstream.adaptive

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        ZIP_NAME_SUFFIX: [webos]
    steps:
    - name: Download webOS NDK
      uses: robinraju/release-downloader@v1.11
      with:
        repository: "openlgtv/buildroot-nc4"
        latest: true
        fileName: "arm-webos-linux-gnueabi_sdk-buildroot-x86_64.tar.gz"
        out-file-path: "/tmp"
    - name: Extract webOS NDK
      working-directory: /tmp
      run: |
        tar xzf arm-webos-linux-gnueabi_sdk-buildroot-x86_64.tar.gz
        ./arm-webos-linux-gnueabi_sdk-buildroot/relocate-sdk.sh
    - name: Checkout Kodi repo
      uses: actions/checkout@v4
      with:
        repository: xbmc/xbmc
        ref: master
        path: xbmc
    - name: Bootstrap depends
      run: |
        cd xbmc/tools/depends
        ./bootstrap
        ./configure --prefix=${{ github.workspace }}/xbmc-deps \
                    --with-toolchain=/tmp/arm-webos-linux-gnueabi_sdk-buildroot --host=arm-webos-linux-gnueabi \
                    --with-platform=webos --enable-debug=no
    - name: Checkout add-on repo
      uses: actions/checkout@v4
      with:
        path: ${{ env.app_id }}
    - name: Configure
      run: |
        cd ${app_id}
        mkdir -p build && cd build
        cmake -DADDONS_TO_BUILD=${app_id} -DADDON_SRC_PREFIX=../.. \
              -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/xbmc/addons \
              -DPACKAGE_ZIP=1 ${{ github.workspace }}/xbmc/cmake/addons
    - name: Build
      run: |
        cd ${app_id}/build
        make
    - name: Run tests
      run: |
        cd ${app_id}/build/${app_id}-prefix/src/${app_id}-build
        make CTEST_OUTPUT_ON_FAILURE=1 GTEST_COLOR=1 test
    - name: Make ZIP artifact
      run: |
        cd ${{ github.workspace }}/xbmc/addons
        zip -r inputstream.adaptive.zip inputstream.adaptive
    - name: Upload zipped artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.app_id }}_${{ matrix.ZIP_NAME_SUFFIX }}.zip
        path: ${{ github.workspace }}/xbmc/addons/inputstream.adaptive.zip
